#!/bin/bash

npm un -S @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @papillonads/components @papillonads/library @svgr/webpack acorn acorn-dynamic-import babel-core babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets classnames clean-webpack-plugin cors css-loader dotenv dotenv-webpack file-loader git-rev-sync glob-all html-webpack-externals-plugin html-webpack-plugin html-webpack-root-plugin ignore-loader imagemin imagemin-gifsicle imagemin-mozjpeg imagemin-optipng imagemin-svgo imagemin-webp imagemin-webp-webpack-plugin img-loader lerna mini-css-extract-plugin moment node-sass npm-run-all optimize-css-assets-webpack-plugin postcss-loader postcss-preset-env postcss-scss prop-types react react-axe react-copy-to-clipboard react-dom react-redux react-router react-router-dom react-transition-group redux redux-logger redux-mock-store redux-thunk regenerator-runtime sass-loader style-loader terser-webpack-plugin uuid webpack webpack-bundle-analyzer webpack-cli webpack-manifest-plugin webpack-merge whatwg-fetch

npm un -D @storybook/addon-actions @storybook/addon-info @storybook/addon-knobs @storybook/addon-links @storybook/addon-notes @storybook/addons @storybook/react @storybook/theming babel-eslint babel-jest codecov enzyme enzyme-adapter-react-16 eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks gh-pages husky identity-obj-proxy jest jest-enzyme lint-staged prettier react-test-renderer stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss

npm i -S @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @papillonads/components @papillonads/library @svgr/webpack acorn acorn-dynamic-import babel-core@^7.0.0-bridge.0 babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets classnames clean-webpack-plugin cors css-loader@^3.6.0 dotenv dotenv-webpack@^2.0.0 file-loader git-rev-sync glob-all html-webpack-externals-plugin html-webpack-plugin@^3.2.0 html-webpack-root-plugin ignore-loader imagemin imagemin-gifsicle imagemin-mozjpeg imagemin-optipng imagemin-svgo imagemin-webp imagemin-webp-webpack-plugin img-loader lerna mini-css-extract-plugin moment node-sass npm-run-all optimize-css-assets-webpack-plugin postcss-loader postcss-preset-env postcss-scss prop-types react react-axe react-copy-to-clipboard react-dom react-redux react-router react-router-dom react-transition-group redux redux-logger redux-mock-store redux-thunk regenerator-runtime sass-loader style-loader terser-webpack-plugin uuid webpack webpack-bundle-analyzer webpack-cli webpack-manifest-plugin webpack-merge whatwg-fetch

npm i -D @storybook/addon-actions @storybook/addon-info @storybook/addon-knobs @storybook/addon-links @storybook/addon-notes @storybook/addons @storybook/react @storybook/theming babel-eslint babel-jest codecov enzyme enzyme-adapter-react-16 eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks gh-pages husky identity-obj-proxy jest jest-enzyme lint-staged prettier react-test-renderer stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss

npm run clean-up && npm run install-packages && npm audit fix && npm run bootstrap
